[v1]
"bandwhich 0.22.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["bandwhich"]
"bat 0.24.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"bottom 0.9.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["btm"]
"du-dust 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["dust"]
"eza 0.18.15 (registry+https://github.com/rust-lang/crates.io-index)" = ["eza"]
"jq 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["jq"]
"kondo 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["kondo"]
"procs 0.14.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["procs"]
"ripgrep 14.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"starship 1.19.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["starship"]
"zoxide 0.9.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide"]
